### ISSUE TITLE
Migrate CI/CD from gitlab to github

### ISSUE THREAD

**Issue by AhmetNSimsek** [FZJ-INM1-BDA/siibra-configurations#1]
from: https://github.com/FZJ-INM1-BDA/siibra-python/issues/540#issuecomment-1898497147

CI pipelines to be migrated:

- [x] Migrate CI/CD pipeline `ci:checklist:generate-update`
- [x] Migrate CI/CD pipeline `ci:test:check_connectivity_json`
- [x] Migrate CI/CD pipeline `ci:test:check_schema`
- [x] Migrate CI/CD pipeline `ci:test:check_jsons`
- [x] Migrate CI/CD pipeline `ci:test:check_ebrains_id`
- [x] Migrate CI/CD pipeline `ci:test:check_map_volume_idx`
- [x] Migrate CI/CD pipeline `ci:test:region_attr_compliance`
- [x] Migrate CI/CD pipeline `ci:test:check_maps`
- [x] Migrate CI/CD pipeline `ci:test:check_maps_precompmesh`
- [x] Migrate CI/CD pipeline `mirror:push_to_mirror`
- [x] Migrate CI/CD pipeline `deploy:okd:sync_to_okd`
- [x] Migrate CI/CD pipeline `deploy:okd:restart_server_pod`
- [x] Migrate CI/CD pipeline `deploy:okd:get_api_queues`
- [x] Migrate CI/CD pipeline `deploy:okd:start_new_worker_pods`

**Comment by xgui3783** [comment]
re: migration of actions prefixed `deploy:` these actions are needed for data validations. 

Currently, ebrain2.0 infrastructure resource quota is too limited to deploy another instance of siibra-api. (this is after we quadrepled our quota in the last month). 

This leaves us with a few options:

- ask the quota at ebrain to be increased again
- deploy an instance of siibra-api else where (e.g. julich VM?)

will check how feasible it is to deploy it at julich.
