### ISSUE TITLE
jba3.0 icbm152 hoc1 left hemisphere statistical map is slightly misaligned

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-configurations#25]
as of [01d3d09](https://github.com/FZJ-INM1-BDA/siibra-python/commit/01d3d095ae8042954bea681cdd76f1bbfd99457d)

code to reproduce

```python
import siibra
julichbrain = siibra.parcellations['julich 3.0']
pmaps = julichbrain.get_map(
    space=siibra.spaces['mni 152'],
    maptype=siibra.MapType.STATISTICAL
)
pmap = pmaps.fetch(region='hoc1 left')
plotting.plot_stat_map(pmap, title=f'hoc1 left of {pmaps.parcellation.name}')
```

results in 

![image](https://user-images.githubusercontent.com/19381783/228340683-f1094c6a-8a2b-412f-bb9e-fa1be015cd25.png)

which is slightly misaligned

**Comment by AhmetNSimsek** [comment]
The same issue as https://github.com/FZJ-INM1-BDA/siibra-configurations/issues/4. Will be tracked there.
