### ISSUE TITLE
[bug] unmatched region references in map

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/siibra-configurations#47]
there exist a few references to regions, which does not exist in parcellation region definition:

```
Following regions in maps/colin27-jba31-labelled.json have no correspondence in parcellation minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-310: ['Area FG5 (FusG) - left hemisphere', 'Area FG5 (FusG) - right hemisphere']
Following regions in maps/mni152-jba31-labelled.json have no correspondence in parcellation minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-310: ['Area FG5 (FusG) - left hemisphere', 'Area FG5 (FusG) - right hemisphere']
Following regions in maps/fsaverage-visfAtlas-labelled.json have no correspondence in parcellation minds/core/parcellationatlas/v1.0.0/d41d8cd98f00b204e9800998ecf8427e: ['lh_hMT', 'lh_v1d', 'lh_v2d', 'lh_v3d', 'lh_v1v', 'lh_v2v', 'lh_v3v', 'rh_pFus_faces', 'rh_hMT', 'rh_v1d', 'rh_v2d', 'rh_v3d', 'rh_v1v', 'rh_v2v', 'rh_v3v']
```

This is generated via `python _ci/verify_maps.py` [link to code](https://github.com/FZJ-INM1-BDA/siibra-configurations/blob/d7f5d0665723dcbfb539fa4518008a63402a8340/_ci/verify_maps.py#L77)

The sanity check silently fails, which can cause a lot of headache. (in fact, I spent about ~2 hr wondering why visf atlas in fsaverage was not displaying correctly). 

I request that the unmatched region sanity check to be turned back on

**Comment by AhmetNSimsek** [comment]
I agree. Do you remember why we turned it off? I can't seem to find or remember
